### ISSUE TITLE
Cache node_modules in GitHub actions

### ISSUE THREAD

**Issue by johannchopin** [johannchopin/gitmoji-browser-extension#36]
Hello Team 👋

**Describe the feature that you want see**

add this config:

```
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
```
